### PR TITLE
Exclude job regex

### PR DESCRIPTION
**Pull request by OlgaMaciaszek**
This PR contains the changes to the Delivery Plugin done by @ArturGajowy (exclude job regex), available here: https://github.com/ArturGajowy/delivery-pipeline-plugin , which I have merged with the most current upstream version.

### CODE REVIEW

**Comment by pskumar448** [comment]
Hi @OlgaMaciaszek 
Instead of having regex to exclude jobs in DPP configuration. Have a look of this PR the implementation of hiding Jobs in DPP can be configured in Job configuration. And also in DPP configuration we have an option to show/hide hidden jobs also there.

PR: https://github.com/Diabol/delivery-pipeline-plugin/pull/169

**Comment by OlgaMaciaszek** [comment]
Hello @pskumar448 
That's a nice PR. However, we reuse the same job for different countries/modules, but then we assemble separate country pipelines, so it makes sense for us show the same job for 1 country with country specific name in one pipeline and another in other country pipeline, but they all stem from the same "build and publish job", so we need a more specific way of managing what appears in the given view, such as the exclude regex that @ArturGajowy has made. 

Anyhow, I see we agree that some approach that would allow hiding jobs from view depending on setup would be useful, but neither your nor our PR has been merged. @patbos , @tommysdk could you reconsider adding this feature to the plugin? It is required by the users. We have ended up setting up another fork in the [company repo](https://github.com/4finance/delivery-pipeline-plugin) just to have it in place and merge @ArturGajowy changes with your upstream changes.

**Comment by tommysdk** [comment]
Hello and thank you for your contribution!

As mentioned in the related issue [JENKINS-26210](https://issues.jenkins-ci.org/browse/JENKINS-26210), we are open to all suggestions on how to meet this need and if there is a way accomplish this in a sensible and intuitive way we would be happy to provide such a feature especially since it has been requested by the community.

Is regex the preferred choice for filtering visualised jobs or have you considered other options? In that case, what are they and what's the reasoning for the proposed solution? Just trying to get an overall understanding of the possibilities here.

A main concern is how to visualize if a hidden task has failed, especially if it is causing the pipeline run to stop. I think this is mainly a concern for users of the aggregated view. Do you have any suggestions? I guess the visualisation concern is more a nice have than a must have for this feature request but I would like the visualisation to be unambiguous in this sense. What are your thoughts on this?

**Comment by OlgaMaciaszek** [comment]
Hello,

thanks for your quick reply :). So our usecase is that all the jobs are being visualised, but in different pipelines. For example, we have 1 repo with the code of the service that is deployed to different contry env. So to have each commit trigger the build and publish to all those envs, we have one build-and-publish-service job and then, say 3 downstream jobs: deploy-service-pl, deploy-service-en, deploy-service-en (in reality there are more steps for every env. flow, but the basic pattern is this). But instead of having one mega pipeline that will show all those running jobs, we have pl pipeline that displays build-and-publish-service--[...]--deploy-service-pl, en pipeline that displays build-and-publish-service--[...]--deploy-service-en, etc.

The regex solution seems to work just fine in our usecase, but if a better one is suggested, we are ready to contribute to that. What is important for us is to have some flexibility while deciding which downstream job should be visible in which pipeline (and not only completely hiding the job).

**Comment by tommysdk** [comment]
@OlgaMaciaszek I understand. I would like to try out the functionality. Could you create a pull request towards Diabol/delivery-pipeline-plugin?

Would it be most user friendly to have the configuraiton on the actual pipeline configuration or toggle visibility in the delivery pipeline configuration for each job?

**Comment by OlgaMaciaszek** [comment]
@tommysdk I will do a PR shortly. I guess it would be easier to do per pipeline, but maybe @ArturGajowy @szpak @marekkapowicki or @pskumar448 have some more suggestions?

**Comment by ArturGajowy** [comment]
@tommysdk I think the place would be `DeliveryPipelineView.java`, which is - AFAIR - configuration of a particular delivery pipeline.

WDYM by 'actual pipeline configuration'? The view I mentioned?

Also, WDYM by 'delivery pipeline configuration for each job'? Global config of the plugin?

**Comment by tommysdk** [comment]
To clarify; should the configuration be per pipeline (as I understand you have with the regex) or for each job that is part of the pipeline - in the section for delivery pipeline configuration (together with stage and task).

**Comment by ArturGajowy** [comment]
Definitely for pipeline. Having it for each job would make our use case impossible to implement.

**Comment by tommysdk** [comment]
@ArturGajowy yes I think so as well. Makes most sense from a user usability perspective.

**Comment by pskumar448** [comment]
@tommysdk @OlgaMaciaszek @ArturGajowy 
I have submitted a PR already with show/hide configuration at Job level and also configuration at DPP show/hide hidden Jobs in pipeline.

Below is the PR.
https://github.com/Diabol/delivery-pipeline-plugin/pull/169

**Comment by ArturGajowy** [comment]
@pskumar448 yes, we've all noticed. It does not fit our use case, though.

**Comment by tommysdk** [comment]
I believe the most important thing is that the solution is intuitive and fits the most use cases for the problem.

Since PR169 upstream is already closed, we'll proceed through PR190.

**Pull request merged**
